### ISSUE TITLE
[META] Check progress

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#169]
4/4からのめやす

### Dennis

* [ ] クーポンサーチAPI 3週間 (#158)
* [ ] クーポンGET API 2週間 (#14)
* [x] 画像関連 JSON API 1.5週間 (#170)

### Okamoto

* [ ] テンプレートファイルの修正 2週間
* [ ] フロントエンド追加対応(画像操作、クーポン削除) 2週間
* [ ] フロントエンドデバグ 1.5週間
* [ ] バックエンドデバグ 0.5週間

**Comment by cdepillabout** [comment]
The 画像関連 JSON API has been implemented in #170.
